[package]
name = "osm-water"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.27.0"
geo-postgis = "0.2.2"
geo-types = "0.7.12"
geozero = "0.11.0"
geozero-shp = "0.4.0"
postgis = "0.9.0"
postgres = "0.19.7"
shapefile = "0.5.0"
wkt = "0.10.3"
